version: '3.9'

services:
  app:
    container_name: docker-practice-app
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./src
        target: /src
    ports:
      - "18000:8000"
    command:
      php -S 0.0.0.0:8000 -t /src
  db:
    container_name: docker-practice-db
    build:
      dockerfile: docker/db/Dockerfile
      context: .
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: event
      MYSQL_USER: hoge
      MYSQL_PASSWORD: pass
    volumes:
      - type: volume
        source: docker-practice-db-volume
        target: /var/lib/mysql
      - type: bind
        source: ./docker/db/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
  mail:
    container_name: docker-practice-mail
    image:
      mailhog/mailhog:v1.0.1
    platform: linux/amd64
    ports:
      - "18025:8025"

volumes:
  docker-practice-db-volume: